### ISSUE TITLE
Missing  exception handling while loading user settings

### ISSUE THREAD

**Issue by KeisukeYamashita** [ogura-edu/HDNNP#207]
This method raises error but there is no handling when calling.
Here is the [link](https://github.com/ogura-edu/HDNNP/blob/4c5273a8be627c708fa3094521cfca959ea39573/hdnnpy/settings.py#L50-L51) to the code.

```python
...
if not Path(search_path, 'settings.py').exists():
    raise FileNotFoundError('`settings.py` is not found in {}'.format(search_path))
...
```

```python
stg = import_user_settings(args)
```

**Comment by ogura-edu** [comment]
Could you tell me if you have any troubles with this issue or if you have an idea of ​​potential bugs that may arise in the future?

**Comment by KeisukeYamashita** [comment]
Sure.  It is actually duplicated stuff of #210.

If you are not planning to error handle, there is no need to use `raise` since the error message is not human friendly.

**Example**

```
Traceback (most recent call last):
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/bin/hdnnpy", line 11, in <module>
    load_entry_point('hdnnpy', 'console_scripts', 'hdnnpy')()
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/hdnnp.py", line 3, in <module>
    from . import settings as stg
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/settings.py", line 69, in <module>
    stg = import_user_settings(args)
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/settings.py", line 51, in import_user_settings
    raise FileNotFoundError('`settings.py` is not found in {}'.format(search_path))
FileNotFoundError: `settings.py` is not found in /Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP
```

`raise` is not a good way to give user feedback.

**Comment by KeisukeYamashita** [comment]
Duplicated with `.xyz` parsing.

```
parsing data/GaN.xyz ... Traceback (most recent call last):
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/bin/hdnnpy", line 11, in <module>
    load_entry_point('hdnnpy', 'console_scripts', 'hdnnpy')()
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/hdnnp.py", line 37, in main
    generator = DataGenerator(stg.dataset.xyz_file, 'xyz')
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/data.py", line 397, in __init__
    self._construct_training_datasets(data_file, format)
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/data.py", line 434, in _construct_training_datasets
    parse_xyzfile(original_xyz)
  File "/Users/keisukeyamashita/Dropbox/go/src/github.com/ogura-edu/HDNNP/hdnnpy/data.py", line 479, in parse_xyzfile
    for atoms in ase.io.iread(str(xyz_file), index=':', format='xyz', parallel=False):
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/ase/io/formats.py", line 503, in iread
    **kwargs):
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/ase/io/formats.py", line 527, in _iread
    fd = open_with_compression(filename, mode)
  File "/Users/keisukeyamashita/.local/share/virtualenvs/HDNNP-D8nCws6U/lib/python3.6/site-packages/ase/io/formats.py", line 313, in open_with_compression
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/GaN.xyz'
```

**Comment by KeisukeYamashita** [comment]
See this one for great infos.

https://stackoverflow.com/questions/16138232/is-it-a-good-practice-to-use-try-except-else-in-python
